### ISSUE TITLE
Verwirrung durch angabe von cpp Files im Tutorial

### ISSUE THREAD

**Issue by LtHustensaft** [tobeyfox/thm-cg#1]
[https://www.tobias-reimann.com/thm/grundlagen-der-computergrafik/cgb_04/](url)

hier werden cgmath.cpp und camera.cpp erstellt, was bei mir fuer Verwirrung gesorgt hat. 

VG
Julian
![Screenshot from 2021-10-31 15-53-03](https://user-images.githubusercontent.com/62930814/139589355-eedfce89-ade7-46a4-85e6-9c8a4c5dcd82.png)

**Comment by tobeyfox** [comment]
Danke für den Hinweis. Ich habe das Tutorial angepasst.
